import { expect, test, type Page } from '@playwright/test'
import { accounts, connectedEnvironment, spaceManagerAccount } from './fixture'

async function login(page: Page) {
  const { password } = await connectedEnvironment()
  await page.goto('/auth')
  await page.getByLabel('이메일').fill(accounts[0].email)
  await page.getByLabel('비밀번호').fill(password)
  await page.locator('form').getByRole('button', { name: '로그인', exact: true }).last().click()
  await expect(page).toHaveURL('/')
}

test('스페이스 생성·전용 관리자·위험 작업은 단계와 확인 모달을 지킨다', async ({ page, browser, baseURL }) => {
  await login(page)
  await page.goto('/spaces')
  await page.getByRole('button', { name: '스페이스 생성', exact: true }).click()
  const wizard = page.getByRole('dialog', { name: '스페이스 생성' })

  await wizard.getByLabel('스페이스 이름').fill('E2E 릴리스 단체')
  await wizard.getByLabel('Slug').fill('e2e-release-space')
  await expect(wizard.getByText('사용 가능')).toBeVisible({ timeout: 10_000 })
  await wizard.getByLabel('설명').fill('스페이스 운영 자동 검증')
  await wizard.getByRole('button', { name: '다음' }).click()

  await wizard.getByLabel('허용 이메일 도메인').fill('@swonport.kr')
  await wizard.getByRole('button', { name: '추가', exact: true }).click()
  await expect(wizard.getByText('@swonport.kr')).toBeVisible()
  await wizard.getByRole('button', { name: '다음' }).click()

  await wizard.getByRole('button', { name: /전용 계정 생성/ }).click()
  await wizard.getByLabel('관리자 이메일').fill(spaceManagerAccount.email)
  await wizard.getByLabel('표시 이름').fill(spaceManagerAccount.nickname)
  await wizard.getByRole('button', { name: '다음' }).click()
  await expect(wizard.getByText(spaceManagerAccount.email)).toBeVisible()
  await wizard.getByRole('button', { name: '스페이스 생성', exact: true }).click()

  const managerCredentials = wizard.locator('.space-created-manager code')
  await expect(managerCredentials).toHaveCount(2, { timeout: 15_000 })
  const managerEmail = (await managerCredentials.nth(0).textContent())?.trim() ?? ''
  const managerPassword = (await managerCredentials.nth(1).textContent())?.trim() ?? ''
  expect(managerEmail).toBe(spaceManagerAccount.email)
  expect(managerPassword.length).toBeGreaterThanOrEqual(12)
  await wizard.getByRole('button', { name: '관리 화면 열기' }).click()
  await expect(page).toHaveURL('/spaces/e2e-release-space/admin')
  await expect(page.getByRole('heading', { name: 'E2E 릴리스 단체' })).toBeVisible()

  const managerContext = await browser.newContext({ baseURL })
  const managerPage = await managerContext.newPage()
  await managerPage.goto('/auth')
  await managerPage.getByLabel('이메일').fill(managerEmail)
  await managerPage.getByLabel('비밀번호').fill(managerPassword)
  await managerPage.locator('form').getByRole('button', { name: '로그인', exact: true }).last().click()
  await expect(managerPage).toHaveURL('/')
  await managerPage.goto('/spaces/e2e-release-space/admin')
  await expect(managerPage.getByRole('heading', { name: 'E2E 릴리스 단체' })).toBeVisible()
  await managerPage.getByRole('button', { name: '설정', exact: true }).click()
  await expect(managerPage.getByLabel('Slug')).toBeDisabled()
  await managerPage.goto('/admin')
  await expect(managerPage.getByRole('heading', { name: '관리자 권한이 필요합니다.' })).toBeVisible()
  await managerContext.close()

  await page.getByRole('button', { name: '멤버', exact: true }).click()
  await page.getByRole('button', { name: '멤버 추가' }).click()
  const memberDialog = page.getByRole('dialog', { name: '멤버 추가' })
  await memberDialog.getByLabel('이메일').fill(accounts[1].email)
  await memberDialog.getByRole('button', { name: '계정 연결', exact: true }).click()
  const guestRow = page.locator('.space-member-row').filter({ hasText: accounts[1].nickname })
  await expect(guestRow).toBeVisible({ timeout: 10_000 })
  await guestRow.getByRole('button', { name: `${accounts[1].nickname} 관리` }).click()
  await page.getByRole('dialog', { name: accounts[1].nickname }).getByRole('button', { name: '스페이스에서 제외' }).click()
  const removeDialog = page.getByRole('dialog', { name: '스페이스에서 제외할까요?' })
  await expect(removeDialog).toContainText('기존 개인 계정 자체는 삭제되지 않습니다.')
  await removeDialog.getByRole('button', { name: '취소' }).click()

  await page.getByRole('dialog', { name: accounts[1].nickname }).getByRole('button', { name: '닫기', exact: true }).last().click()
  await page.getByRole('button', { name: '설정', exact: true }).click()
  await page.getByRole('button', { name: '스페이스 보관' }).click()
  const archiveDialog = page.getByRole('dialog', { name: '스페이스를 보관할까요?' })
  await expect(archiveDialog).toBeVisible()
  await archiveDialog.getByRole('button', { name: '취소' }).click()

  await page.goto('/cards')
  await page.getByRole('button', { name: '새 카드 세트' }).click()
  const createCard = page.getByRole('dialog', { name: '새 카드 세트' })
  await createCard.getByLabel('이름').fill('E2E 삭제 확인 카드')
  await createCard.getByRole('button', { name: '생성', exact: true }).click()
  const card = page.locator('article').filter({ hasText: 'E2E 삭제 확인 카드' })
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: '삭제' }).click()
  const cardDelete = page.getByRole('dialog', { name: '카드 세트를 삭제할까요?' })
  await expect(cardDelete).toContainText('E2E 삭제 확인 카드')
  await cardDelete.getByRole('button', { name: '취소' }).click()
  await expect(card).toBeVisible()
})
