import { expect, test, type Page } from '@playwright/test'
import { accounts, connectedEnvironment, spaceManagerAccount } from './fixture'

async function login(page: Page) {
  const { password } = await connectedEnvironment()
  await page.goto('/auth')
  await page.getByLabel('이메일').fill(accounts[0].email)
  await page.getByLabel('비밀번호').fill(password)
  await page.locator('form').getByRole('button', { name: '로그인', exact: true }).last().click()
  await expect(page).toHaveURL('/')
}

test('위험한 스페이스·카드 작업은 정식 확인 모달을 거친다', async ({ page, browser }) => {
  await login(page)
  await page.goto('/account')
  await page.evaluate(() => {
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new DOMException('denied', 'NotAllowedError') } } })
    Object.defineProperty(document, 'execCommand', { configurable: true, value: () => false })
  })
  await page.getByRole('button', { name: '친구 태그 복사' }).click()
  await expect(page.getByRole('alert')).toContainText('친구 태그를 복사하지 못했어요.')

  await page.addInitScript(() => {
    Reflect.deleteProperty(window, 'PushManager')
  })
  await page.goto('/friends')
  const unsupportedPush = page.getByRole('button', { name: '이 브라우저는 알림 미지원' })
  await expect(unsupportedPush).toBeVisible()
  await expect(unsupportedPush).toBeDisabled()

  await page.goto('/spaces')
  await page.getByRole('button', { name: '스페이스 생성', exact: true }).click()
  const createSpace = page.getByRole('dialog', { name: '스페이스 생성' })
  await expect(createSpace.getByRole('button', { name: '관리 URL 복사' })).toBeDisabled()
  await createSpace.getByLabel('이름', { exact: true }).fill('E2E 릴리스 단체')
  await createSpace.getByRole('textbox', { name: 'Slug', exact: true }).fill('e2e-release-space')
  await createSpace.getByLabel('관리자 이메일').fill(spaceManagerAccount.email)
  await createSpace.getByLabel('관리자 표시 이름').fill(spaceManagerAccount.nickname)
  await createSpace.getByLabel('기관 이메일 도메인').fill('swonport.kr')
  await createSpace.getByLabel('설명').fill('위험 작업 모달 자동 검증')
  await createSpace.getByRole('button', { name: '스페이스와 관리자 생성', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('@example.org 형식')
  await expect(createSpace).toBeVisible()
  await createSpace.getByLabel('기관 이메일 도메인').fill('@@swonport.kr')
  await createSpace.getByRole('button', { name: '스페이스와 관리자 생성', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('@example.org 형식')
  await createSpace.getByLabel('기관 이메일 도메인').fill(' @SWONPORT.KR ')
  await expect(createSpace.getByLabel('기관 이메일 도메인')).toHaveValue('@swonport.kr')
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => undefined } }))
  await createSpace.getByRole('button', { name: '관리 URL 복사' }).click()
  await expect(page.getByRole('status')).toContainText('관리 URL을 복사했어요.')
  await createSpace.getByRole('button', { name: '스페이스와 관리자 생성', exact: true }).click()
  await expect(createSpace.getByRole('status')).toContainText('스페이스 관리자 로그인 정보')
  const managerCredentials = createSpace.locator('.space-created-manager code')
  await expect(managerCredentials).toHaveCount(2)
  const managerEmail = (await managerCredentials.nth(0).textContent())?.trim() ?? ''
  const managerPassword = (await managerCredentials.nth(1).textContent())?.trim() ?? ''
  expect(managerEmail).toBe(spaceManagerAccount.email)
  expect(managerPassword.length).toBeGreaterThanOrEqual(12)
  await createSpace.getByRole('button', { name: '관리 화면 열기', exact: true }).click()
  await expect(page).toHaveURL('/spaces/e2e-release-space/admin', { timeout: 15_000 })

  const managerContext = await browser.newContext({ baseURL: 'http://127.0.0.1:43131' })
  const managerPage = await managerContext.newPage()
  await managerPage.goto('/auth')
  await managerPage.getByLabel('이메일').fill(managerEmail)
  await managerPage.getByLabel('비밀번호').fill(managerPassword)
  await managerPage.locator('form').getByRole('button', { name: '로그인', exact: true }).last().click()
  await expect(managerPage).toHaveURL('/')
  await managerPage.goto('/spaces/e2e-release-space/admin')
  await expect(managerPage.getByRole('heading', { name: 'E2E 릴리스 단체 관리' })).toBeVisible()
  await expect(managerPage.getByText('허용 이메일: @swonport.kr')).toBeVisible()
  await managerPage.goto('/admin')
  await expect(managerPage.getByRole('heading', { name: '관리자 권한이 필요합니다.' })).toBeVisible()
  await managerContext.close()

  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => undefined } }))
  await page.getByRole('button', { name: '링크 복사' }).click()
  await expect(page.getByRole('status')).toContainText('가입 링크를 복사했어요.')

  await page.getByRole('button', { name: '설정', exact: true }).click()
  await page.getByRole('button', { name: '스페이스 비활성화' }).click()
  const archiveDialog = page.getByRole('dialog', { name: '스페이스를 비활성화할까요?' })
  await expect(archiveDialog).toBeVisible()
  await archiveDialog.getByRole('button', { name: '취소' }).click()
  await expect(archiveDialog).toBeHidden()

  await page.getByRole('button', { name: '멤버', exact: true }).click()
  await page.getByRole('button', { name: '멤버 추가' }).click()
  const memberDialog = page.getByRole('dialog', { name: '멤버 추가' })
  await memberDialog.getByLabel('이메일').fill(accounts[1].email)
  await memberDialog.getByRole('button', { name: '추가', exact: true }).click()
  const guestRow = page.locator('.space-member-row').filter({ hasText: accounts[1].nickname })
  await expect(guestRow).toBeVisible()
  await guestRow.getByRole('button', { name: `${accounts[1].nickname} 삭제` }).click()
  const memberDelete = page.getByRole('dialog', { name: '멤버를 삭제할까요?' })
  await expect(memberDelete).toContainText(accounts[1].nickname)
  await memberDelete.getByRole('button', { name: '취소' }).click()

  await page.goto('/cards')
  await page.getByRole('button', { name: '새 카드 세트' }).click()
  const createCard = page.getByRole('dialog', { name: '새 카드 세트' })
  await createCard.getByLabel('이름').fill('E2E 삭제 확인 카드')
  await createCard.getByRole('button', { name: '생성', exact: true }).click()
  const card = page.locator('article').filter({ hasText: 'E2E 삭제 확인 카드' })
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: '삭제' }).click()
  const cardDelete = page.getByRole('dialog', { name: '카드 세트를 삭제할까요?' })
  await expect(cardDelete).toContainText('E2E 삭제 확인 카드')
  await cardDelete.getByRole('button', { name: '취소' }).click()
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: '삭제' }).click()
  await page.getByRole('dialog', { name: '카드 세트를 삭제할까요?' }).getByRole('button', { name: '삭제하기' }).click()
  await expect(card).toBeHidden({ timeout: 15_000 })
})
