-- Physical card integrity and the server implementation of constrained-rounds-v1.
-- A collected card may be revealed again only after returning to draw; its
-- reveal_generation distinguishes that legal lifecycle from a duplicate reveal.

alter table public.game_cards
  add column if not exists reveal_generation integer not null default 0
    check (reveal_generation >= 0);

alter table public.games
  add column if not exists shuffle_metadata jsonb not null default '{}'::jsonb;

create unique index if not exists game_cards_draw_order_unique_idx
  on public.game_cards(game_id, holder_id, pile_order)
  where zone = 'draw';

create unique index if not exists game_cards_face_order_unique_idx
  on public.game_cards(game_id, pile_order)
  where zone = 'face_up';

create table if not exists public.game_card_transitions (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  card_id uuid not null references public.game_cards(id) on delete cascade,
  from_zone text check (from_zone is null or from_zone in ('draw', 'face_up')),
  to_zone text not null check (to_zone in ('draw', 'face_up')),
  reveal_generation integer not null,
  game_version integer,
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists game_card_transitions_trace_idx
  on public.game_card_transitions(game_id, card_id, id);
alter table public.game_card_transitions enable row level security;
revoke all on table public.game_card_transitions from public, anon, authenticated;

create or replace function public.log_game_card_transition()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.zone is not distinct from new.zone
     and old.holder_id is not distinct from new.holder_id then
    return new;
  end if;

  begin
    insert into public.game_card_transitions(
      game_id, card_id, from_zone, to_zone, reveal_generation, game_version, reason
    ) values (
      new.game_id,
      new.id,
      old.zone,
      new.zone,
      new.reveal_generation,
      (select version from public.games where id = new.game_id),
      case
        when old.zone = 'draw' and new.zone = 'face_up' then 'reveal'
        when old.zone = 'face_up' and new.zone = 'draw' then 'bell_collection'
        when old.holder_id is distinct from new.holder_id then 'ownership_transfer'
        else 'zone_change'
      end
    );
  exception when others then
    -- Diagnostics must never interrupt gameplay.
    raise warning 'game_card_transition_log_failed game_id=% card_id=%', new.game_id, new.id;
  end;
  return new;
end;
$$;

revoke all on function public.log_game_card_transition() from public, anon, authenticated;
drop trigger if exists log_game_card_transition_trigger on public.game_cards;
create trigger log_game_card_transition_trigger
after update of zone, holder_id on public.game_cards
for each row execute function public.log_game_card_transition();

create or replace function public.reject_duplicate_card_reveal_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.event_type = 'reveal'
     and new.payload ? 'cardId'
     and new.payload ? 'revealGeneration'
     and exists (
       select 1
       from public.game_events previous
       where previous.game_id = new.game_id
         and previous.event_type = 'reveal'
         and previous.payload ->> 'cardId' = new.payload ->> 'cardId'
         and previous.payload ->> 'revealGeneration' = new.payload ->> 'revealGeneration'
     ) then
    raise log 'CRITICAL duplicate_card_reveal game_id=% card_id=% action_id=%',
      new.game_id, new.payload ->> 'cardId', new.action_id;
    raise exception using message = 'duplicate_card_reveal', errcode = 'P0001';
  end if;
  return new;
end;
$$;

revoke all on function public.reject_duplicate_card_reveal_event() from public, anon, authenticated;
drop trigger if exists reject_duplicate_card_reveal_event_trigger on public.game_events;
create trigger reject_duplicate_card_reveal_event_trigger
before insert on public.game_events
for each row execute function public.reject_duplicate_card_reveal_event();

create unique index if not exists game_events_card_reveal_generation_unique_idx
  on public.game_events(
    game_id,
    ((payload ->> 'cardId')::uuid),
    ((payload ->> 'revealGeneration')::integer)
  )
  where event_type = 'reveal'
    and payload ? 'cardId'
    and payload ? 'revealGeneration';

create or replace function public.deal_game_card_snapshot(
  p_game_id uuid,
  p_player_ids uuid[],
  p_snapshot jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  player_count integer := coalesce(array_length(p_player_ids, 1), 0);
  base_cards jsonb[];
  candidate jsonb[];
  best_candidate jsonb[];
  start_seat integer;
  best_start_seat integer := 0;
  attempt integer;
  repeated_player_faces integer;
  repeated_consecutive_rounds integer;
  repeated_recent_two_player_rounds integer;
  score integer;
  best_score integer := 2147483647;
  dealt_count integer;
begin
  if player_count < 2 or player_count > 6 or jsonb_typeof(p_snapshot -> 'designs') <> 'array' then
    raise exception using message = 'invalid_card_set_snapshot', errcode = 'P0001';
  end if;

  with designs as (
    select
      design ->> 'fruit_type' as fruit,
      (design ->> 'fruit_count')::smallint as fruit_count,
      greatest(1, least(12, (design ->> 'quantity')::integer)) as copies
    from jsonb_array_elements(p_snapshot -> 'designs') design
    where design ->> 'fruit_type' in ('strawberry', 'banana', 'lime', 'plum')
      and (design ->> 'fruit_count')::integer between 1 and 5
      and (design ->> 'quantity')::integer between 1 and 12
  )
  select array_agg(jsonb_build_object(
    'id', gen_random_uuid()::text,
    'fruit', fruit,
    'count', fruit_count
  ) order by fruit, fruit_count, copy)
  into base_cards
  from designs cross join lateral generate_series(1, copies) as copy;

  if coalesce(array_length(base_cards, 1), 0) < player_count then
    raise exception using message = 'invalid_card_set_snapshot', errcode = 'P0001';
  end if;

  for attempt in 1..256 loop
    select array_agg(card order by random()) into candidate
    from unnest(base_cards) as shuffled(card);
    start_seat := floor(random() * player_count)::integer;

    with dealt as (
      select
        ordinality::integer as position,
        ((start_seat + ordinality::integer - 1) % player_count) + 1 as seat,
        ((ordinality::integer - 1) / player_count) + 1 as round_number,
        (card ->> 'fruit') || ':' || (card ->> 'count') as face
      from unnest(candidate) with ordinality as cards(card, ordinality)
    ), player_repeats as (
      select count(*)::integer as count
      from dealt current_card
      join dealt previous_card
        on previous_card.seat = current_card.seat
       and previous_card.round_number = current_card.round_number - 1
       and previous_card.face = current_card.face
    ), rounds as (
      select
        round_number,
        string_agg(face, '|' order by seat) as ordered_faces,
        string_agg(face, '|' order by face) as sorted_faces,
        count(*) as card_count
      from dealt
      group by round_number
    ), consecutive_rounds as (
      select count(*)::integer as count
      from rounds current_round
      join rounds previous_round
        on previous_round.round_number = current_round.round_number - 1
       and previous_round.ordered_faces = current_round.ordered_faces
    ), recent_two_player_rounds as (
      select count(*)::integer as count
      from rounds current_round
      join rounds previous_round
        on player_count = 2
       and current_round.card_count = 2
       and previous_round.card_count = 2
       and previous_round.round_number between current_round.round_number - 4 and current_round.round_number - 1
       and previous_round.sorted_faces = current_round.sorted_faces
    )
    select player_repeats.count, consecutive_rounds.count, recent_two_player_rounds.count
    into repeated_player_faces, repeated_consecutive_rounds, repeated_recent_two_player_rounds
    from player_repeats, consecutive_rounds, recent_two_player_rounds;

    score := repeated_player_faces * 100
      + repeated_consecutive_rounds * 20
      + repeated_recent_two_player_rounds * 5;
    if score < best_score then
      best_candidate := candidate;
      best_start_seat := start_seat;
      best_score := score;
    end if;
    exit when score = 0;
  end loop;

  if best_candidate is null then
    raise exception using message = 'shuffle_failed', errcode = 'P0001';
  end if;
  if best_score > 0 then
    raise warning 'constrained_shuffle_fallback game_id=% score=% attempts=256', p_game_id, best_score;
  end if;

  with dealt as (
    select
      card,
      ((best_start_seat + ordinality::integer - 1) % player_count) + 1 as seat,
      ((ordinality::integer - 1) / player_count) + 1 as pile_order
    from unnest(best_candidate) with ordinality as cards(card, ordinality)
  ), inserted as (
    insert into public.game_cards(id, game_id, holder_id, zone, pile_order, fruit, fruit_count)
    select
      (card ->> 'id')::uuid,
      p_game_id,
      p_player_ids[seat],
      'draw',
      pile_order,
      card ->> 'fruit',
      (card ->> 'count')::smallint
    from dealt
    returning 1
  )
  select count(*) into dealt_count from inserted;

  update public.games
  set shuffle_metadata = jsonb_build_object(
    'policy', 'constrained-rounds-v1',
    'attempts', attempt,
    'usedFallback', best_score > 0,
    'violationScore', best_score,
    'startSeat', best_start_seat
  )
  where id = p_game_id;

  if dealt_count <> array_length(base_cards, 1) then
    raise exception using message = 'shuffle_card_count_changed', errcode = 'P0001';
  end if;
  return dealt_count;
end;
$$;

revoke all on function public.deal_game_card_snapshot(uuid, uuid[], jsonb) from public, anon, authenticated;

-- Preserve the mature completion/ranking logic and attach physical card IDs to
-- every snapshot returned by any existing game function.
alter function public.refresh_game_snapshot(uuid) rename to refresh_game_snapshot_base;
revoke all on function public.refresh_game_snapshot_base(uuid) from public, anon, authenticated;

create function public.refresh_game_snapshot(p_game_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  snapshot jsonb;
  table_cards jsonb;
  last_result jsonb;
begin
  snapshot := public.refresh_game_snapshot_base(p_game_id);

  with top_cards as (
    select distinct on (card.holder_id)
      card.id,
      card.holder_id,
      card.fruit,
      card.fruit_count,
      player.seat
    from public.game_cards card
    join public.game_players player
      on player.game_id = card.game_id and player.user_id = card.holder_id
    where card.game_id = p_game_id and card.zone = 'face_up'
    order by card.holder_id, card.pile_order desc
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'cardId', id,
    'userId', holder_id,
    'fruit', fruit,
    'count', fruit_count
  ) order by seat), '[]'::jsonb)
  into table_cards
  from top_cards;

  select jsonb_build_object(
    'type', event_type,
    'userId', user_id,
    'actionId', action_id,
    'cardId', payload ->> 'cardId',
    'correct', case when event_type = 'ring' then (payload ->> 'correct')::boolean else null end,
    'fruit', payload ->> 'fruit',
    'count', case when payload ? 'count' then (payload ->> 'count')::integer else null end
  )
  into last_result
  from public.game_events
  where game_id = p_game_id
  order by id desc
  limit 1;

  snapshot := jsonb_set(snapshot, '{table}', table_cards, true);
  if last_result is not null then
    snapshot := jsonb_set(snapshot, '{lastResult}', last_result, true);
  end if;
  update public.games set state = snapshot where id = p_game_id;
  return snapshot;
end;
$$;

revoke all on function public.refresh_game_snapshot(uuid) from public, anon, authenticated;

create or replace function public.reveal_game_card(p_game_id uuid, p_action_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  locked_game public.games;
  selected_card public.game_cards;
  current_seat smallint;
  next_player uuid;
  snapshot jsonb;
  effective_action_id uuid := coalesce(p_action_id, gen_random_uuid());
  next_reveal_generation integer;
  updated_count integer;
begin
  select * into locked_game from public.games where id = p_game_id for update;
  if locked_game.id is null then raise exception 'game not found'; end if;
  if not public.is_game_member(p_game_id) then raise exception 'not a game member'; end if;
  if p_action_id is not null and exists (
    select 1 from public.game_events where game_id = p_game_id and action_id = p_action_id
  ) then return locked_game.state; end if;
  if locked_game.finished_at is not null then raise exception 'game is not active'; end if;
  if exists (
    select 1 from public.game_players where game_id = p_game_id and user_id = auth.uid()
      and (abandoned_at is not null or eliminated_at is not null)
  ) then raise exception 'player eliminated'; end if;
  if locked_game.current_turn <> auth.uid() then raise exception 'not your turn'; end if;

  select * into selected_card
  from public.game_cards
  where game_id = p_game_id and holder_id = auth.uid() and zone = 'draw'
  order by pile_order
  limit 1
  for update;
  if selected_card.id is null then raise exception 'no cards to reveal'; end if;

  next_reveal_generation := selected_card.reveal_generation + 1;
  if exists (
    select 1 from public.game_events
    where game_id = p_game_id and event_type = 'reveal'
      and payload ->> 'cardId' = selected_card.id::text
      and (payload ->> 'revealGeneration')::integer = next_reveal_generation
  ) then
    raise log 'CRITICAL duplicate_card_reveal game_id=% card_id=% action_id=%',
      p_game_id, selected_card.id, effective_action_id;
    raise exception using message = 'duplicate_card_reveal', errcode = 'P0001';
  end if;

  update public.game_cards
  set zone = 'face_up',
      pile_order = locked_game.version + 1,
      reveal_generation = next_reveal_generation
  where id = selected_card.id and zone = 'draw';
  get diagnostics updated_count = row_count;
  if updated_count <> 1 then
    raise log 'CRITICAL duplicate_card_reveal_race game_id=% card_id=% action_id=%',
      p_game_id, selected_card.id, effective_action_id;
    raise exception using message = 'duplicate_card_reveal', errcode = 'P0001';
  end if;

  update public.game_players
  set revealed_cards = revealed_cards + 1
  where game_id = p_game_id and user_id = auth.uid();

  select seat into current_seat
  from public.game_players
  where game_id = p_game_id and user_id = auth.uid();
  select player.user_id into next_player
  from public.game_players player
  where player.game_id = p_game_id
    and player.abandoned_at is null
    and player.eliminated_at is null
    and exists (
      select 1 from public.game_cards card
      where card.game_id = p_game_id and card.holder_id = player.user_id and card.zone = 'draw'
    )
  order by case when player.seat > current_seat then 0 else 1 end, player.seat
  limit 1;

  update public.games
  set version = version + 1, current_turn = coalesce(next_player, auth.uid())
  where id = p_game_id;
  insert into public.game_events(game_id, user_id, event_type, action_id, payload)
  values (p_game_id, auth.uid(), 'reveal', effective_action_id, jsonb_build_object(
    'cardId', selected_card.id,
    'revealGeneration', next_reveal_generation,
    'fruit', selected_card.fruit,
    'count', selected_card.fruit_count,
    'version', locked_game.version + 1
  ));
  snapshot := public.refresh_game_snapshot(p_game_id);
  return snapshot;
end;
$$;

revoke all on function public.reveal_game_card(uuid, uuid) from public, anon;
grant execute on function public.reveal_game_card(uuid, uuid) to authenticated;

comment on function public.deal_game_card_snapshot(uuid, uuid[], jsonb) is
  'Bounded constrained-rounds-v1 shuffle shared with bot practice policy semantics.';
comment on column public.game_cards.reveal_generation is
  'Increments only on draw-to-face_up, allowing legal post-collection reveals while rejecting duplicate publication.';
